# Generated by Django 5.2.7 on 2025-11-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_category_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminder_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
